name = "magicerase"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./.vercel/output/static"

[vars]
CLIPDROP_API_KEY = "YOUR_CLIPDROP_API_KEY"

# For Cloudflare Pages deployment
[pages_build_output_dir]
